# Generated by Django 2.1.7 on 2019-04-01 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='descreption',
            new_name='description',
        ),
    ]
